export default [
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/08/92489251-AC40-42FF-BC8A-F608E316F3BE-scaled.jpeg",
    name: "Samuel Ayomide",
    language: "English",
    rating: 4.5,
    price: 80,
    walkings: 83,
    city: "🇳🇬 Ibadan - Nigeria",
  },
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/08/WhatsApp-Image-2022-08-09-at-14.40.23-640x600.jpeg",
    name: "Jake S.",
    language: "English",
    rating: 5,
    price: 75,
    walkings: 61,
    city: "🇺🇸 New York - EUA",
  },
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/07/Foto-Pedro-Jardim-de-Mattos-693x600.jpg",
    name: "Vanessa Pascale",
    language: "French",
    rating: 4.7,
    price: 75,
    walkings: 97,
    city: "🇧🇷 São paulo - Brazil",
  },
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/06/foto-logo.jpg",
    name: "Fábio A.",
    language: "English",
    rating: 4.7,
    price: 75,
    walkings: 73,
    city: "🇧🇷 Rio de Janeiro - Brazil",
  },
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/06/perfilargentina-720x600.jpeg",
    name: "Aide Paixão",
    language: "Spanish",
    rating: 4.4,
    price: 63,
    walkings: 89,
    city: "🇧🇷 Rio de Janeiro - Brazil",
  },
  {
    imageUrl:
      "https://talkawaylanguage.com/wp-content/uploads/2022/06/Mohammedperfil-e1654561292611-640x600.jpeg",
    name: " Mohammed El Jazoul",
    language: "Arabian",
    rating: 4.4,
    price: 63,
    walkings: 103,
    city: "🇧🇷 Rio de Janeiro - Brazil",
  },
  {
    imageUrl: "",
    name: "Anna Garcia",
    language: "Spanish",
    rating: 4.5,
    price: 65,
    walkings: 107,
    city: "🇺🇸 New York - USA",
  },
  {
    imageUrl: "",
    name: "Koji Nakamura",
    language: "Japanese",
    rating: 4.8,
    price: 68,
    walkings: 109,
    city: "🇯🇵 Tokyo - Japan",
  },
  {
    imageUrl: "",
    name: "Sophie Laurent",
    language: "French",
    rating: 4.6,
    price: 71,
    walkings: 113,
    city: "🇫🇷 Paris - France",
  },
  {
    imageUrl: "",
    name: "Luca Rossi",
    language: "Italian",
    rating: 4.3,
    price: 73,
    walkings: 127,
    city: "🇮🇹 Rome - Italy",
  },
  {
    imageUrl: "",
    name: "Tomasz Kowalski",
    language: "Polish",
    rating: 4.9,
    price: 79,
    walkings: 131,
    city: "🇵🇱 Warsaw - Poland",
  },
  {
    imageUrl: "",
    name: "Lina Chen",
    language: "Mandarin Chinese",
    rating: 4.5,
    price: 83,
    walkings: 137,
    city: "🇨🇳 Beijing - China",
  },
  {
    imageUrl: "",
    name: "Rita da Silva",
    language: "Portuguese",
    rating: 4.6,
    price: 89,
    walkings: 139,
    city: "🇧🇷 São Paulo - Brazil",
  },
  {
    imageUrl: "",
    name: "Sergei Ivanov",
    language: "Russian",
    rating: 4.7,
    price: 97,
    walkings: 149,
    city: "🇷🇺 Moscow - Russia",
  },
  {
    imageUrl: "",
    name: "Maria Hernandez",
    language: "Spanish",
    rating: 4.4,
    price: 101,
    walkings: 151,
    city: "🇪🇸 Madrid - Spain",
  },
  {
    imageUrl: "",
    name: "Jung-Sook Lee",
    language: "Korean",
    rating: 4.5,
    price: 103,
    walkings: 157,
    city: "🇰🇷 Seoul - South Korea",
  },

  {
    imageUrl: "",
    name: "Marco Rossi",
    language: "Italian",
    rating: 4.7,
    price: 107,
    walkings: 163,
    city: "🇮🇹 Milan - Italy",
  },
  {
    imageUrl: "",
    name: "Fatima Ahmad",
    language: "Arabic",
    rating: 4.4,
    price: 109,
    walkings: 167,
    city: "🇪🇬 Cairo - Egypt",
  },
  {
    imageUrl: "",
    name: "John Smith",
    language: "English",
    rating: 4.6,
    price: 113,
    walkings: 173,
    city: "🇬🇧 London - UK",
  },
  {
    imageUrl: "",
    name: "Carlos Santos",
    language: "Portuguese",
    rating: 4.8,
    price: 127,
    walkings: 179,
    city: "🇧🇷 Salvador - Brazil",
  },
  {
    imageUrl: "",
    name: "Hiroshi Takahashi",
    language: "Japanese",
    rating: 4.5,
    price: 131,
    walkings: 181,
    city: "🇯🇵 Osaka - Japan",
  },
  {
    imageUrl: "",
    name: "Maria Garcia",
    language: "Spanish",
    rating: 4.7,
    price: 137,
    walkings: 191,
    city: "🇲🇽 Mexico City - Mexico",
  },
  {
    imageUrl: "",
    name: "Katja Schmidt",
    language: "German",
    rating: 4.4,
    price: 139,
    walkings: 193,
    city: "🇩🇪 Berlin - Germany",
  },
  {
    imageUrl: "",
    name: "Mikhail Ivanov",
    language: "Russian",
    rating: 4.5,
    price: 149,
    walkings: 197,
    city: "🇷🇺 St. Petersburg - Russia",
  },
  {
    imageUrl: "",
    name: "Carla Fernandes",
    language: "Portuguese",
    rating: 4.4,
    price: 151,
    walkings: 199,
    city: "🇵🇹 Lisbon - Portugal",
  },
];
