export default {
  COLORS: {
    TANGERINE: "#FF9D48",
    GOLDEN: "#FFCD6C",
    CRIMSON: "#B61430",
    INDIGO: "#177D8F",
  },
  FONTS: {
    OS_LT_CONDENSED: "OPENSANS_LIGHT_CONDENSED",
    OS_MD_CONDENSED: "OPENSANS_MEDIUM_CONDENSED",
    OS_RG_CONDENSED: "OPENSANS_REGULAR_CONDENSED",
    OS_BD_CONDENSED: "OPENSANS_BOLD_CONDENSED",
    OS_LT: "OPENSANS_LIGHT",
    OS_MD: "OPENSANS_MEDIUM",
    OS_RG: "OPENSANS_REGULAR",
    OS_BD: "OPENSANS_BOLD",
  },
};
